/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Jupiter.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Material #1088']}
        geometry={nodes.Jupiter.geometry}
        position={[0, 0, -7.15]}
        rotation={[-Math.PI / 9, 0, 0]}
        scale={[0.08, 0.08, 0.08]}
      >
        <meshStandardMaterial color="yellow" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Jupiter.glb')
