/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Mercury.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Mercury}
        geometry={nodes.Mercury.geometry}
        position={[-0.01, 0, -0.01]}
        rotation={[0.27, 1.07, -1.82]}
        scale={[2.0, 2.0, 2.0]}
      ><meshStandardMaterial color="red" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Mercury.glb')
