/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Sun.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Sun}
        geometry={nodes.Sun.geometry}
        position={[0, 0, 0.01]}
        scale={[1.93, 1.93, 1.93]}
      ><meshStandardMaterial color="#FFD341" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Sun.glb')
