/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Uranus.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Uranus}
        geometry={nodes.Uranus.geometry}
        position={[0, 0.46, 0]}
        rotation={[0, -0.35, -1.59]}
        scale={[0.94, 0.94, 0.94]}
      ><meshStandardMaterial color="blue" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Uranus.glb')
